import type { PermissionKey, RoleConfig, RoleKey } from "@/lib/types";

export const roleConfigs: Record<RoleKey, RoleConfig> = {
  SUPER_ADMIN: {
    role: "SUPER_ADMIN",
    name: "Rhea Menon",
    title: "Super admin",
    initials: "RM",
    dashboardTitle: "Platform overview",
    accessSummary: "Manage hospitals, administrators, system controls, and platform reports.",
    permissions: [
      "dashboard",
      "hospitals",
      "hospital_admins",
      "system",
      "reports",
      "notifications",
      "audit_logs",
      "settings",
    ],
    nav: [
      { label: "Dashboard", href: "/super-admin/dashboard", icon: "LayoutDashboard", permission: "dashboard" },
      { label: "Hospitals", href: "/super-admin/hospitals", icon: "Building2", permission: "hospitals" },
      { label: "Admins", href: "/super-admin/hospital-admins", icon: "Users", permission: "hospital_admins" },
      { label: "System", href: "/super-admin/system", icon: "ShieldCheck", permission: "system" },
      { label: "Reports", href: "/super-admin/reports", icon: "BarChart3", permission: "reports" },
      { label: "Audit Logs", href: "/super-admin/audit-logs", icon: "FileText", permission: "audit_logs" },
    ],
  },
  HOSPITAL_ADMIN: {
    role: "HOSPITAL_ADMIN",
    name: "Asha Sharma",
    title: "Hospital administrator",
    initials: "AS",
    dashboardTitle: "Hospital command center",
    accessSummary: "View hospital-wide staff, patients, clinical operations, billing, and revenue reports.",
    permissions: [
      "dashboard",
      "hospital_staff",
      "doctors",
      "patients",
      "appointments",
      "opd",
      "ipd",
      "emergency",
      "referrals",
      "laboratory",
      "pharmacy",
      "radiology",
      "billing",
      "reports",
      "notifications",
      "audit_logs",
      "settings",
    ],
    nav: [
      { label: "Dashboard", href: "/hospital/dashboard", icon: "LayoutDashboard", permission: "dashboard" },
      { label: "Staff", href: "/hospital/staff", icon: "Users", permission: "hospital_staff" },
      { label: "Appointments", href: "/hospital/appointments", icon: "CalendarDays", permission: "appointments" },
      { label: "OPD", href: "/hospital/opd", icon: "ClipboardList", permission: "opd" },
      { label: "IPD", href: "/hospital/ipd", icon: "BedDouble", permission: "ipd" },
      { label: "Emergency", href: "/hospital/emergency", icon: "AlertTriangle", permission: "emergency" },
      { label: "Referrals", href: "/hospital/referrals", icon: "FileText", permission: "referrals" },
      { label: "Laboratory", href: "/hospital/laboratory", icon: "FlaskConical", permission: "laboratory" },
      { label: "Pharmacy", href: "/hospital/pharmacy", icon: "Pill", permission: "pharmacy" },
      { label: "Billing", href: "/hospital/billing", icon: "WalletCards", permission: "billing" },
      { label: "Reports", href: "/hospital/reports", icon: "FileBarChart2", permission: "reports" },
    ],
  },
  RECEPTIONIST: {
    role: "RECEPTIONIST",
    name: "Neha Kulkarni",
    title: "Receptionist",
    initials: "NK",
    dashboardTitle: "Front desk overview",
    accessSummary: "Register patients, create appointments, manage front-desk records, and collect billing payments.",
    permissions: ["dashboard", "patients", "appointments", "billing", "notifications"],
    nav: [
      { label: "Dashboard", href: "/reception/dashboard", icon: "LayoutDashboard", permission: "dashboard" },
      { label: "Patients", href: "/reception/patients", icon: "Users", permission: "patients" },
      { label: "Appointments", href: "/reception/appointments", icon: "CalendarDays", permission: "appointments" },
      { label: "Admissions", href: "/reception/admissions", icon: "ClipboardList", permission: "patients" },
      { label: "Billing", href: "/reception/billing", icon: "WalletCards", permission: "billing" },
    ],
  },
  DOCTOR: {
    role: "DOCTOR",
    name: "Dr. Dev Nair",
    title: "Consultant physician",
    initials: "DN",
    dashboardTitle: "Clinical dashboard",
    accessSummary: "View assigned patient records, document consultations, and update clinical care information.",
    permissions: ["dashboard", "patients", "appointments", "opd", "notifications"],
    nav: [
      { label: "Dashboard", href: "/doctor/dashboard", icon: "LayoutDashboard", permission: "dashboard" },
      { label: "Appointments", href: "/doctor/appointments", icon: "CalendarDays", permission: "appointments" },
      { label: "Patients", href: "/doctor/patients", icon: "Users", permission: "patients" },
      { label: "Consultations", href: "/doctor/consultations", icon: "ClipboardList", permission: "opd" },
      { label: "Schedule", href: "/doctor/schedule", icon: "CalendarCheck2", permission: "appointments" },
    ],
  },
  LAB_MANAGER: {
    role: "LAB_MANAGER",
    name: "Priya Menon",
    title: "Lab manager",
    initials: "PM",
    dashboardTitle: "Laboratory operations",
    accessSummary: "Process doctor-created lab orders, manage samples, verify results, and publish lab reports.",
    permissions: ["dashboard", "laboratory", "reports", "notifications"],
    nav: [
      { label: "Dashboard", href: "/lab/dashboard", icon: "LayoutDashboard", permission: "dashboard" },
      { label: "Orders", href: "/lab/orders", icon: "FlaskConical", permission: "laboratory" },
      { label: "Results", href: "/lab/results", icon: "FileText", permission: "laboratory" },
      { label: "Reports", href: "/lab/reports", icon: "BarChart3", permission: "reports" },
    ],
  },
  LAB_TECHNICIAN: {
    role: "LAB_TECHNICIAN",
    name: "Zaid Khan",
    title: "Lab technician",
    initials: "ZK",
    dashboardTitle: "Sample workflow",
    accessSummary: "Work on assigned samples and enter laboratory results within the lab workflow.",
    permissions: ["dashboard", "laboratory", "notifications"],
    nav: [
      { label: "Dashboard", href: "/lab/dashboard", icon: "LayoutDashboard", permission: "dashboard" },
      { label: "Assigned Tests", href: "/lab/assigned-tests", icon: "FlaskConical", permission: "laboratory" },
      { label: "Results", href: "/lab/results", icon: "FileText", permission: "laboratory" },
    ],
  },
  PHARMACIST: {
    role: "PHARMACIST",
    name: "Shivani Rao",
    title: "Pharmacist",
    initials: "SR",
    dashboardTitle: "Medication center",
    accessSummary: "Manage prescriptions, medication dispensing, inventory, and pharmacy reports.",
    permissions: ["dashboard", "pharmacy", "notifications"],
    nav: [
      { label: "Dashboard", href: "/pharmacy/dashboard", icon: "LayoutDashboard", permission: "dashboard" },
      { label: "Prescriptions", href: "/pharmacy/prescriptions", icon: "FileText", permission: "pharmacy" },
      { label: "Inventory", href: "/pharmacy/inventory", icon: "Pill", permission: "pharmacy" },
      { label: "Reports", href: "/pharmacy/reports", icon: "BarChart3", permission: "pharmacy" },
    ],
  },
  ACCOUNTANT: {
    role: "ACCOUNTANT",
    name: "Nikhil Joshi",
    title: "Accountant",
    initials: "NJ",
    dashboardTitle: "Finance dashboard",
    accessSummary: "Manage invoices, payments, balances, and finance reports.",
    permissions: ["dashboard", "billing", "reports"],
    nav: [
      { label: "Dashboard", href: "/accounts/dashboard", icon: "LayoutDashboard", permission: "dashboard" },
      { label: "Invoices", href: "/accounts/invoices", icon: "ReceiptText", permission: "billing" },
      { label: "Payments", href: "/accounts/payments", icon: "CreditCard", permission: "billing" },
      { label: "Reports", href: "/accounts/reports", icon: "BarChart3", permission: "reports" },
    ],
  },
  STAFF: {
    role: "STAFF",
    name: "Aditi Pawar",
    title: "Staff member",
    initials: "AP",
    dashboardTitle: "Team workspace",
    accessSummary: "View assigned staff notifications and team updates.",
    permissions: ["dashboard", "notifications"],
    nav: [
      { label: "Dashboard", href: "/staff/dashboard", icon: "LayoutDashboard", permission: "dashboard" },
      { label: "Notifications", href: "/staff/notifications", icon: "Bell", permission: "notifications" },
    ],
  },
};

export const roleOptions = Object.values(roleConfigs).map((config) => ({
  id: config.role,
  label: config.title,
  description: config.dashboardTitle,
  accessSummary: config.accessSummary,
}));

export const isRoleAllowed = (role: RoleKey, permission: PermissionKey) =>
  roleConfigs[role].permissions.includes(permission);
