"use client";

import { useState } from "react";
import { CalendarDays, ChevronRight, FileCheck2, Search, Stethoscope, Users, X } from "lucide-react";
import { categoryLabels, initialPatients } from "@/lib/hms-data";
import type { PatientCategory, PatientRecord } from "@/lib/hms-types";
import { ActivityTable, Bar, DataPanel, MetricStrip, QueueItem, WorkspaceHeader } from "@/components/dashboard-widgets";
import { BellRing, BedDouble, CreditCard, WalletCards } from "lucide-react";

export function AdminDashboard() {
  return <><WorkspaceHeader eyebrow="Hospital command center" title="Good morning, Asha" copy="A clear view of Royal Care, from patient flow to performance." /><MetricStrip items={[{ label: "Total patients", value: "1,248", detail: "↑ 8.4% this month", icon: Users, tone: "blue" }, { label: "Today&apos;s appointments", value: "64", detail: "↑ 12.1% vs Tuesday", icon: CalendarDays, tone: "mint" }, { label: "Bed occupancy", value: "74%", detail: "31 beds available", icon: BedDouble, tone: "amber" }, { label: "Monthly collections", value: "₹28.4L", detail: "↑ 6.8% vs last month", icon: WalletCards, tone: "rose" }]} /><div className="workspace-grid"><DataPanel title="Operational pulse" kicker="At a glance" className="admin-pulse"><div className="admin-bars"><Bar label="Patient satisfaction" value="92%" width="92%" tone="mint" /><Bar label="Staff attendance" value="87%" width="87%" tone="blue" /><Bar label="Claim settlement" value="76%" width="76%" tone="amber" /></div><div className="admin-stat-row"><div><strong>42</strong><span>Current admissions</span></div><div><strong>18</strong><span>Pending lab orders</span></div><div><strong>07</strong><span>Discharges today</span></div></div></DataPanel><DataPanel title="Needs attention" kicker="Admin queue" action="View all"><QueueItem icon={BellRing} tone="rose" title="3 critical incidents" detail="Awaiting administrator review" /><QueueItem icon={Users} tone="blue" title="24 new registrations" detail="Since yesterday afternoon" /><QueueItem icon={CreditCard} tone="amber" title="₹4.2L receivables" detail="Due from insurance partners" /></DataPanel></div><ActivityTable title="Recent hospital activity" rows={["New patient registered · Meera Iyer", "Discharge approved · Ward 3", "Monthly roster published · Nursing", "Vendor invoice received · Pharmacy"]} /></>;
}

export function AdminPatientsPage() {
  const [category, setCategory] = useState<PatientCategory | "ALL">("ALL");
  const [search, setSearch] = useState("");
  const [selectedPatient, setSelectedPatient] = useState<PatientRecord | null>(null);

  return <><WorkspaceHeader eyebrow="Patient administration" title="Patient registry" copy="Review patient groups, search records, and open complete patient profiles." /><AdminPatientRegistry patients={initialPatients} category={category} search={search} onCategoryChange={setCategory} onSearchChange={setSearch} onSelect={setSelectedPatient} />{selectedPatient && <PatientDetails patient={selectedPatient} onClose={() => setSelectedPatient(null)} />}</>;
}

function AdminPatientRegistry({ patients, category, search, onCategoryChange, onSearchChange, onSelect }: { patients: PatientRecord[]; category: PatientCategory | "ALL"; search: string; onCategoryChange: (category: PatientCategory | "ALL") => void; onSearchChange: (search: string) => void; onSelect: (patient: PatientRecord) => void }) {
  const categories: { id: PatientCategory | "ALL"; label: string }[] = [{ id: "ALL", label: "All patients" }, { id: "OP", label: "Outpatient (OP)" }, { id: "IP", label: "Inpatient (IP)" }, { id: "REFERRAL", label: "Referral" }, { id: "EMERGENCY", label: "Emergency" }];
  const visiblePatients = patients.filter((patient) => (category === "ALL" || patient.category === category) && `${patient.name} ${patient.uhid}`.toLowerCase().includes(search.toLowerCase()));
  return <section className="panel admin-patient-panel"><div className="panel-heading"><div><span className="panel-kicker">Patient management</span><h2>Patient registry</h2><p className="panel-subtitle">Browse every patient group and open their complete record.</p></div></div><div className="patient-toolbar"><div className="patient-tabs">{categories.map((item) => <button key={item.id} className={category === item.id ? "active" : ""} onClick={() => onCategoryChange(item.id)}>{item.label}<b>{item.id === "ALL" ? patients.length : patients.filter((patient) => patient.category === item.id).length}</b></button>)}</div><div className="registry-search"><Search size={15} /><input value={search} onChange={(event) => onSearchChange(event.target.value)} placeholder="Search name or UHID" />{search && <button onClick={() => onSearchChange("")} aria-label="Clear patient search"><X size={14} /></button>}</div></div><div className="admin-patient-list"><div className="admin-patient-list-head"><span>Patient</span><span>Category</span><span>Doctor / department</span><span>Status</span><span /></div>{visiblePatients.map((patient) => <button className="admin-patient-row" key={patient.id} onClick={() => onSelect(patient)}><span className="patient-cell"><span className="patient-avatar">{patient.name.split(" ").map((part) => part[0]).join("")}</span><span><strong>{patient.name}</strong><small>{patient.uhid} · {patient.age} yrs · {patient.gender}</small></span></span><span className={`type-pill ${patient.category.toLowerCase()}`}>{categoryLabels[patient.category]}</span><span className="patient-doctor"><strong>{patient.doctor}</strong><small>{patient.department}</small></span><span className={`status-pill ${patient.status.toLowerCase()}`}><i />{patient.status}</span><ChevronRight size={17} /></button>)}{visiblePatients.length === 0 && <div className="empty-patients"><Users size={20} /><strong>No patients found</strong><span>Try another search.</span></div>}</div></section>;
}

function PatientDetails({ patient, onClose }: { patient: PatientRecord; onClose: () => void }) {
  return <div className="drawer-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="patient-drawer" role="dialog" aria-modal="true" aria-labelledby="patient-detail-title"><div className="drawer-top"><div><span className="panel-kicker">Patient profile</span><h2 id="patient-detail-title">{patient.name}</h2><span className="drawer-uhid">{patient.uhid}</span></div><button className="icon-button light" onClick={onClose} aria-label="Close patient details"><X size={17} /></button></div><div className="drawer-identity"><div className="large-patient-avatar">{patient.name.split(" ").map((part) => part[0]).join("")}</div><div><span className={`type-pill ${patient.category.toLowerCase()}`}>{categoryLabels[patient.category]}</span><span className={`status-pill ${patient.status.toLowerCase()}`}><i />{patient.status}</span></div></div><div className="detail-section"><span className="form-section-title">Patient information</span><div className="detail-grid"><Detail label="Age / gender" value={`${patient.age} years · ${patient.gender}`} /><Detail label="Blood group" value={patient.bloodGroup} /><Detail label="Phone" value={patient.phone} /><Detail label="Registered" value={patient.registered} /><Detail label="Address" value={patient.address} wide /><Detail label="Allergies" value={patient.allergies} wide /></div></div><div className="detail-section"><span className="form-section-title">Care team</span><div className="care-team-row"><span className="queue-icon blue"><Stethoscope size={16} /></span><div><strong>{patient.doctor}</strong><span>{patient.department}</span></div><ChevronRight size={16} /></div></div><div className="drawer-actions"><button className="button secondary"><FileCheck2 size={15} /> View records</button><button className="button primary"><CalendarDays size={15} /> Book appointment</button></div></aside></div>;
}

function Detail({ label, value, wide = false }: { label: string; value: string; wide?: boolean }) { return <div className={wide ? "detail-item wide" : "detail-item"}><span>{label}</span><strong>{value}</strong></div>; }
