import { BedDouble, BellRing, CalendarDays, CheckCircle2, CreditCard, FileCheck2, FlaskConical, HeartPulse, UserRound, Users, Clock3 } from "lucide-react";
import { ActivityTable, Bar, DataPanel, MetricStrip, QuickAction, QueueItem, ScheduleRow, WorkspaceHeader } from "@/components/dashboard-widgets";

export function DoctorDashboard() {
  return <><WorkspaceHeader eyebrow="Clinical workspace" title="Good morning, Dr. Sharma" copy="Your rounds, appointments and care priorities for today." action="New consultation" actionIcon={HeartPulse} /><MetricStrip items={[{ label: "Today&apos;s appointments", value: "12", detail: "4 consultations next", icon: CalendarDays, tone: "blue" }, { label: "Patients on rounds", value: "18", detail: "6 require review", icon: BedDouble, tone: "mint" }, { label: "Critical alerts", value: "03", detail: "Need attention now", icon: BellRing, tone: "rose" }, { label: "Pending orders", value: "09", detail: "5 lab · 4 imaging", icon: FileCheck2, tone: "amber" }]} /><div className="workspace-grid"><DataPanel title="Today&apos;s schedule" kicker="Monday · 12 appointments" action="View calendar"><ScheduleRow time="09:30" name="Meera Iyer" detail="Follow-up · OPD 02" tone="blue" /><ScheduleRow time="10:15" name="Arjun Nair" detail="Post-op review · Ward 3" tone="mint" /><ScheduleRow time="11:00" name="Fatima Khan" detail="Discharge assessment · ICU" tone="rose" /><ScheduleRow time="12:30" name="Rohan Deshmukh" detail="New consultation · OPD 02" tone="amber" /></DataPanel><DataPanel title="Care priorities" kicker="Clinical attention"><QueueItem icon={HeartPulse} tone="rose" title="SpO₂ 88% · ICU-04" detail="Fatima Khan · 12 minutes ago" /><QueueItem icon={FlaskConical} tone="amber" title="CBC result ready" detail="Arjun Nair · Review required" /><QueueItem icon={FileCheck2} tone="blue" title="2 discharge requests" detail="Awaiting your sign-off" /></DataPanel></div><ActivityTable title="Recently viewed patients" rows={["Meera Iyer · Follow-up notes updated", "Arjun Nair · Medication order renewed", "Fatima Khan · Vitals flagged by nursing", "Rohan Deshmukh · Referral attached"]} /></>;
}

export function ReceptionDashboard() {
  return <><WorkspaceHeader eyebrow="Front desk workspace" title="Good morning, Neha" copy="Keep arrivals moving and every patient welcomed." action="Register patient" /><MetricStrip items={[{ label: "Arrivals today", value: "38", detail: "11 waiting to check-in", icon: Users, tone: "blue" }, { label: "Appointments", value: "64", detail: "18 still to arrive", icon: CalendarDays, tone: "mint" }, { label: "Registration queue", value: "07", detail: "Average wait 8 min", icon: Clock3, tone: "amber" }, { label: "Outstanding payments", value: "₹86K", detail: "14 invoices open", icon: CreditCard, tone: "rose" }]} /><div className="workspace-grid"><DataPanel title="Front desk queue" kicker="Live arrivals" action="Open queue"><QueueItem icon={Clock3} tone="amber" title="Rahul Menon · 08:45" detail="Waiting for registration · OPD 01" /><QueueItem icon={CheckCircle2} tone="mint" title="Sana Sheikh · 09:00" detail="Checked in · Dr. Mehta" /><QueueItem icon={Clock3} tone="blue" title="Vikram Joshi · 09:15" detail="Payment pending · OPD 03" /><QueueItem icon={BellRing} tone="rose" title="Emergency arrival" detail="Triage desk notified · 2 minutes ago" /></DataPanel><DataPanel title="Quick actions" kicker="Common tasks"><div className="quick-actions"><QuickAction icon={UserRound} label="Register patient" /><QuickAction icon={CalendarDays} label="Book appointment" /><QuickAction icon={CreditCard} label="Collect payment" /><QuickAction icon={FileCheck2} label="Print token" /></div></DataPanel></div><ActivityTable title="Today&apos;s reception activity" rows={["Patient checked in · Sana Sheikh", "Appointment rescheduled · OPD 03", "Payment received · ₹2,400", "Insurance card scanned · Rahul Menon"]} /></>;
}

export function LabDashboard() {
  return <><WorkspaceHeader eyebrow="Laboratory workspace" title="Good morning, Priya" copy="Your laboratory queue, results and quality checks in one view." action="Create lab order" actionIcon={FlaskConical} /><MetricStrip items={[{ label: "Pending samples", value: "26", detail: "8 urgent · 18 routine", icon: FlaskConical, tone: "blue" }, { label: "Results to verify", value: "14", detail: "4 critical values", icon: FileCheck2, tone: "mint" }, { label: "Average turnaround", value: "42m", detail: "↓ 8 min this week", icon: Clock3, tone: "amber" }, { label: "Quality score", value: "98.6%", detail: "Within target range", icon: CheckCircle2, tone: "rose" }]} /><div className="workspace-grid"><DataPanel title="Sample workflow" kicker="26 samples in progress" action="View laboratory"><Bar label="Collected" value="26" width="100%" tone="blue" /><Bar label="In processing" value="14" width="54%" tone="amber" /><Bar label="Awaiting verification" value="08" width="31%" tone="mint" /><Bar label="Released today" value="64" width="78%" tone="rose" /></DataPanel><DataPanel title="Critical results" kicker="Immediate review"><QueueItem icon={BellRing} tone="rose" title="Potassium 6.8 mmol/L" detail="ICU-04 · Fatima Khan · 2 min ago" /><QueueItem icon={HeartPulse} tone="rose" title="Troponin I elevated" detail="ER-12 · Sameer Rao · 11 min ago" /><QueueItem icon={CheckCircle2} tone="mint" title="3 criticals acknowledged" detail="All care teams notified" /></DataPanel></div><ActivityTable title="Latest lab activity" rows={["CBC verified · Arjun Nair · Dr. Sharma notified", "Blood sample received · ICU-04", "Lipid profile released · OPD 02", "Reagent inventory checked · Hematology"]} /></>;
}
